version: "3"
services:
  app:
    build: mysite/.
    depends_on:
      - db_mysql
    container_name: django
    restart: always
    ports:
      - "8000:8000"
    command:
      "python manage.py runserver 0.0.0.0:8000"

  db_mysql:
    image: mariadb:10
    container_name: db_mysql
    ports:
      - "33006:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: rootpass
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

